typography_spectrum: 0.6564126822631806
color:
  brandStrength: 0.9459980074316263
  lightness: 0.27005068585276604
  saturation: 0.26264809537678957
  rhythmicContrast: 0.3703210342209786
  brandColors:
    - '#FF8000'
    - '#FFD933'
    - '#CCCC52'
    - '#8FB359'
    - '#192B33'
layout_spectrum: 0.02666456252336502
name: 'hjh kjhj llkjlk '
navigation:
  - name: '122'
    id: 08ba6019-44e0-423d-97fe-3c09d0e395de
    type: content
  - name: '55555'
    url: www.sfdas.sk
    type: external
title: 6566+
description: '1111'
